### ISSUE TITLE
Borrow request causes error if no mainImage object element is present

### ISSUE THREAD

**Issue by limecakeio** [limecakeio/PrimeTree#96]
Error: TypeError: co.listing.mainImage is undefined

Reproduce: Load the home screen until the borrow requests appears. Error should show up in console. Reason may be that I check within borrow-request-preview-html if no image is available, in which case I display an icon for the borrow requests. However, this results in the rest of the listings failing to load. 

Stack Trace:

>ERROR TypeError: co.listing.mainImage is undefined
Stack trace:
View_BorrowRequestPreviewComponent_0/<@ng:///BorrowRequestModule/BorrowRequestPreviewComponent.ngfactory.js:135:9
updateDirectives@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12426:63
checkAndUpdateView@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12025:5
callViewAction@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12340:17
execComponentViewsAction@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12286:13
checkAndUpdateView@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12031:5
callViewAction@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12340:17
execEmbeddedViewsAction@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12312:17
checkAndUpdateView@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12026:5
callViewAction@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12340:17
execEmbeddedViewsAction@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12312:17
checkAndUpdateView@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12026:5
callViewAction@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12340:17
execEmbeddedViewsAction@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12312:17
checkAndUpdateView@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12026:5
callViewAction@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12340:17
execComponentViewsAction@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12286:13
checkAndUpdateView@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12031:5
callViewAction@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12340:17
execEmbeddedViewsAction@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12312:17
checkAndUpdateView@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12026:5
callViewAction@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12340:17
execComponentViewsAction@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12286:13
checkAndUpdateView@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:12031:5
ViewRef_.prototype.detectChanges@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:10122:54
ApplicationRef_.prototype.tick/<@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:5059:58
ApplicationRef_.prototype.tick@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:5059:13
next/<@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:4939:100
ZoneDelegate.prototype.invoke@https://unpkg.com/zone.js@0.8.5?main=browser:365:17
onInvoke@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:4132:28
ZoneDelegate.prototype.invoke@https://unpkg.com/zone.js@0.8.5?main=browser:364:17
Zone.prototype.run@https://unpkg.com/zone.js@0.8.5?main=browser:125:24
NgZone.prototype.run@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:4001:51
next@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:4939:70
EventEmitter.prototype.subscribe/schedulerFn<@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:3835:36
SafeSubscriber.prototype.__tryOrUnsub@http://localhost:3000/node_modules/rxjs/Subscriber.js:223:13
SafeSubscriber.prototype.next@http://localhost:3000/node_modules/rxjs/Subscriber.js:172:17
Subscriber.prototype._next@http://localhost:3000/node_modules/rxjs/Subscriber.js:125:9
Subscriber.prototype.next@http://localhost:3000/node_modules/rxjs/Subscriber.js:89:13
Subject.prototype.next@http://localhost:3000/node_modules/rxjs/Subject.js:55:17
EventEmitter.prototype.emit@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:3821:54
NgZone.prototype.checkStable@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:4097:17
NgZone.prototype.onLeave@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:4173:9
onInvokeTask@http://localhost:3000/node_modules/@angular/core/bundles/core.umd.js:4126:21
ZoneDelegate.prototype.invokeTask@https://unpkg.com/zone.js@0.8.5?main=browser:397:17
Zone.prototype.runTask@https://unpkg.com/zone.js@0.8.5?main=browser:165:28
ZoneTask/this.invoke@https://unpkg.com/zone.js@0.8.5?main=browser:460:28
timer@https://unpkg.com/zone.js@0.8.5?main=browser:1540:17

**Comment by 1520152NPHSM** [comment]
fixed
